
import com.google.gson.Gson;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.JOptionPane.showMessageDialog;
import org.json.simple.*;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import shares.Exception_Exception;
import shares.FileNotFoundException_Exception;
import shares.IOException_Exception;
import shares.JAXBException_Exception;
import shares.ListSharesResponse;
import shares.MalformedURLException_Exception;
import shares.ParseException_Exception;
import shares.UpdateCurrencyPriceResponse;
import shares.UpdatePriceXMLResponse;
import shares.UpdateSharesResponse;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bensw
 */
public class ShareClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ShareClientGUI
     */

    public ShareClientGUI() {
        
        initComponents();
        autoLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        label6 = new java.awt.Label();
        textField6 = new java.awt.TextField();
        label11 = new java.awt.Label();
        jFrame1 = new javax.swing.JFrame();
        scrollPane1 = new java.awt.ScrollPane();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        jComboBox1 = new javax.swing.JComboBox<>();
        label12 = new java.awt.Label();
        saveConvertCurr = new java.awt.Button();
        ConvertedField = new java.awt.TextField();
        convertBtn1 = new java.awt.Button();
        button2 = new java.awt.Button();
        panel2 = new java.awt.Panel();
        label8 = new java.awt.Label();
        label2 = new java.awt.Label();
        compSymbolField = new java.awt.TextField();
        label4 = new java.awt.Label();
        avSharesField = new java.awt.TextField();
        label5 = new java.awt.Label();
        priceField = new java.awt.TextField();
        label7 = new java.awt.Label();
        currencyField = new java.awt.TextField();
        compNameField = new java.awt.TextField();
        label1 = new java.awt.Label();
        button3 = new java.awt.Button();
        panel3 = new java.awt.Panel();
        button4 = new java.awt.Button();
        detailsListBox = new java.awt.List();
        updateShares = new java.awt.Button();
        jSpinner1 = new javax.swing.JSpinner();
        listNamesListBox = new java.awt.List();
        listNamesBtn = new java.awt.Button();
        removeCompany = new java.awt.Button();
        label10 = new java.awt.Label();
        panel4 = new java.awt.Panel();
        label9 = new java.awt.Label();
        searchListBox = new java.awt.List();
        nameSearchField = new java.awt.TextField();
        searchSymbolBtn = new java.awt.Button();
        symbolSearchField = new java.awt.TextField();
        searchNameBtn1 = new java.awt.Button();
        highPriceBtn = new java.awt.Button();
        button1 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        textField2 = new java.awt.TextField();
        jSpinner2 = new javax.swing.JSpinner();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        jSpinner3 = new javax.swing.JSpinner();
        textField1 = new java.awt.TextField();
        label13 = new java.awt.Label();

        label3.setText("Company Symbol");

        textField3.setText("textField1");

        label6.setText("Share Price");

        label11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        label11.setText("View All Companies");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox1.setModel(getArray());
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 63, 204, 46));

        label12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label12.setText("Convert Share Price");
        panel1.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 0, -1, -1));

        saveConvertCurr.setActionCommand("Convert To");
        saveConvertCurr.setBackground(new java.awt.Color(255, 255, 255));
        saveConvertCurr.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        saveConvertCurr.setLabel("Convert To");
        saveConvertCurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveConvertCurrActionPerformed(evt);
            }
        });
        panel1.add(saveConvertCurr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 211, 46));

        ConvertedField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        panel1.add(ConvertedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 425, 42));

        convertBtn1.setActionCommand("Save Convert");
        convertBtn1.setBackground(new java.awt.Color(255, 255, 255));
        convertBtn1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        convertBtn1.setLabel("Save Conversion");
        convertBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtn1ActionPerformed(evt);
            }
        });
        panel1.add(convertBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 187, 425, 40));

        button2.setBackground(new java.awt.Color(255, 255, 255));
        button2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        button2.setLabel("Convert All");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 246, 425, 41));

        panel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label8.setText("Add Companies");
        panel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 0, -1, -1));

        label2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label2.setText("Company Symbol");
        panel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        compSymbolField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        panel2.add(compSymbolField, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 87, 164, -1));

        label4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label4.setText("Available Shares");
        panel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 334, -1));

        avSharesField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        panel2.add(avSharesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 128, 164, -1));

        label5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label5.setText("Share Price");
        panel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));

        priceField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        panel2.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 169, 164, -1));

        label7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label7.setText("Currency");
        panel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 206, -1, -1));

        currencyField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        panel2.add(currencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 206, 164, -1));

        compNameField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        panel2.add(compNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 44, 164, -1));

        label1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label1.setText("Company Name");
        panel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, -1, -1));

        button3.setBackground(new java.awt.Color(255, 255, 255));
        button3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        button3.setLabel("Add Company");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        panel2.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, 508, 41));

        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button4.setBackground(new java.awt.Color(255, 255, 255));
        button4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        button4.setLabel("Update Share Price");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        panel3.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, 439, 43));

        detailsListBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        detailsListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsListBoxActionPerformed(evt);
            }
        });
        panel3.add(detailsListBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 85, 239, 149));

        updateShares.setBackground(new java.awt.Color(255, 255, 255));
        updateShares.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        updateShares.setLabel("Update Shares");
        updateShares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSharesActionPerformed(evt);
            }
        });
        panel3.add(updateShares, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 244, 239, -1));
        panel3.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 190, 31));

        listNamesListBox.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        listNamesListBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listNamesListBoxMouseEntered(evt);
            }
        });
        listNamesListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listNamesListBoxActionPerformed(evt);
            }
        });
        panel3.add(listNamesListBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 190, 149));
        listNamesListBox.getAccessibleContext().setAccessibleName("listNamesBox");

        listNamesBtn.setActionCommand("listNamesBtn");
        listNamesBtn.setBackground(new java.awt.Color(255, 255, 255));
        listNamesBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        listNamesBtn.setLabel("List Companies");
        listNamesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listNamesBtnActionPerformed(evt);
            }
        });
        panel3.add(listNamesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 190, -1));
        listNamesBtn.getAccessibleContext().setAccessibleName("listNamesBtn");

        removeCompany.setBackground(new java.awt.Color(255, 255, 255));
        removeCompany.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        removeCompany.setLabel("Remove Company");
        removeCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCompanyActionPerformed(evt);
            }
        });
        panel3.add(removeCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 44, 239, -1));

        label10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label10.setText("View All Companies");
        panel3.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label9.setText("Search Companies");
        panel4.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        searchListBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchListBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchListBoxActionPerformed(evt);
            }
        });
        panel4.add(searchListBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 126, 492, 68));

        nameSearchField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nameSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameSearchFieldMouseClicked(evt);
            }
        });
        nameSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchFieldActionPerformed(evt);
            }
        });
        panel4.add(nameSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 44, 184, 31));

        searchSymbolBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchSymbolBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchSymbolBtn.setLabel("Search Symbol");
        searchSymbolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSymbolBtnActionPerformed(evt);
            }
        });
        panel4.add(searchSymbolBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 85, 298, -1));

        symbolSearchField.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        symbolSearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                symbolSearchFieldMouseClicked(evt);
            }
        });
        symbolSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolSearchFieldActionPerformed(evt);
            }
        });
        panel4.add(symbolSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 85, 184, 31));

        searchNameBtn1.setBackground(new java.awt.Color(255, 255, 255));
        searchNameBtn1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchNameBtn1.setLabel("Search Name");
        searchNameBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameBtn1ActionPerformed(evt);
            }
        });
        panel4.add(searchNameBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 44, 298, -1));

        highPriceBtn.setBackground(new java.awt.Color(255, 255, 255));
        highPriceBtn.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        highPriceBtn.setLabel("Search Highest Price");
        highPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highPriceBtnActionPerformed(evt);
            }
        });
        panel4.add(highPriceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 249, 492, 37));

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        button1.setLabel("Search Lowest Price");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel4.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 296, 492, 39));

        button5.setLabel("button5");
        panel4.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        button6.setBackground(new java.awt.Color(255, 255, 255));
        button6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        button6.setLabel("Search Prices");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        panel4.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 207, 186, -1));

        textField2.setText("textField2");
        panel4.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));
        panel4.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 207, 75, 31));

        label14.setText("label14");
        panel4.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        label15.setText("label15");
        panel4.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        label16.setText("label16");
        panel4.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        label17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label17.setText("-");
        panel4.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 204, -1, -1));
        panel4.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 204, 75, 35));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textField1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        label13.setText("Ben Swift");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(346, 346, 346)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void autoLoad(){
            try {
            // TODO add your handling code here:
            textField1.setText("Loading...");
            for (int i = 0; i < listNames().size() ;i++ )
            {
                
                listNamesListBox.add(listNames().get(i));
            }
            textField1.setText("");
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        try {
            // TODO add your handling code here:

            String name = "";
            int updatedPrice = 0;
            //for (int i=0; i < listNames().size(); i++)
            //{
                name = listNamesListBox.getSelectedItem();
                if (listNamesListBox.getSelectedItem() == null )
                {
                    showMessageDialog(null, "No company selected");
                }
                else{
                    textField1.setText("Updating...");
                    updatedPrice = (int) Math.round(updateSharePrice2(listSymbol(name)));
                    updatePriceXML(updatedPrice,name);
                    textField1.setText("");
                }
                
                //}
        } catch (IOException ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void removeCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCompanyActionPerformed
        // TODO add your handling code here:
        try {
            if (listNamesListBox.getSelectedItem() == null)
            {
                showMessageDialog(null, "Select a company to delete");
            }
            else
            {
                String name = listNamesListBox.getSelectedItem();
                removeCompany(name);
                listNamesListBox.removeAll();
                detailsListBox.removeAll();
                for (int i = 0; i < listNames().size() ;i++ )
                {
                    listNamesListBox.add(listNames().get(i));
                }
            }
        } catch (JAXBException_Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException_Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeCompanyActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        try {
            if (compNameField.getText().isEmpty() || compSymbolField.getText().isEmpty() || avSharesField.getText().isEmpty() ||  priceField.getText().isEmpty() )
            {
                showMessageDialog(null,"No company information provided");
            }
            else{
                textField1.setText("Adding new company:"+compNameField.getText() + "...");
                int avShares = Integer.parseInt(avSharesField.getText());
                int sharePrice = Integer.parseInt(priceField.getText());
                addCompany(compNameField.getText(),compSymbolField.getText(),avShares, sharePrice,currencyField.getText());
                avSharesField.setText("");
                priceField.setText("");
                compNameField.setText("");
                currencyField.setText("");
                compSymbolField.setText("");
                textField1.setText("");
            }
        } catch (IOException_Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException_Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        String name = new String();
        int selectedCode = 0;
        //name = listNamesListBox.getSelectedItem();
        selectedCode = jComboBox1.getSelectedIndex();
        String currency = new String();
        double newPrice = 0;
        String newCurrency = new String();
        int valueBefore = 0;
        try {
            if (ConvertedField.getText().isEmpty())
            {
                showMessageDialog(null,"Select a currency to convert to");
            }
            else{
                textField1.setText("Updating...");
                for (int i =0; i < listNames().size();i++)
                {
                    name = listNames().get(i);
                    currency = listCurrency(name);
                    valueBefore = listPrice(name);
                    newCurrency = getCurrencyCodes().get(selectedCode).substring(0, 3);
                    newPrice = convert(currency,newCurrency,valueBefore);
                    updateCurrencyPrice(newCurrency,newPrice,name);
                }
                textField1.setText("");
                listNamesListBox.removeAll();
                detailsListBox.removeAll();
                for (int i = 0; i < listNames().size();i++ )
                {
                    listNamesListBox.add(listNames().get(i));
                }
                        }
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void convertBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtn1ActionPerformed
        String name = new String();
        int selectedCode = 0;
        name = listNamesListBox.getSelectedItem();
        selectedCode = jComboBox1.getSelectedIndex();
        String currency = new String();
        double newPrice = 0;
        String newCurrency = new String();
        int valueBefore = 0;
        try {
            if (ConvertedField.getText().isEmpty())
            {
                showMessageDialog(null,"Select a currency to convert to");
            }
            else{
                currency = listCurrency(name);
                valueBefore = listPrice(name);
                newCurrency = getCurrencyCodes().get(selectedCode).substring(0, 3);
                newPrice = convert(currency,newCurrency,valueBefore);
                updateCurrencyPrice(newCurrency,newPrice,name);
                listNamesListBox.removeAll();
                detailsListBox.removeAll();
                for (int i = 0; i < listNames().size();i++ )
                {
                    listNamesListBox.add(listNames().get(i));
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_convertBtn1ActionPerformed

    private void updateSharesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSharesActionPerformed
        String name = new String();
        name = listNamesListBox.getSelectedItem();
        String currency = new String();

        String newCurrency = new String();
        int newShares = 0;

        try {
            if (listNamesListBox.getSelectedItem() == null )
            {
                showMessageDialog(null, "Please select a company to update");
            }
            else{
                //newShares = Integer.parseInt(newSharesField.getText());
                newShares = (int) jSpinner1.getValue();
                updateShares(name,newShares);
                listNamesListBox.removeAll();
                detailsListBox.removeAll();
                for (int i = 0; i < listNames().size();i++ )
                {
                    listNamesListBox.add(listNames().get(i));
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateSharesActionPerformed

    private void saveConvertCurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveConvertCurrActionPerformed
        String name = new String();
        int selectedCode = 0;
        name = listNamesListBox.getSelectedItem();
        selectedCode = jComboBox1.getSelectedIndex();
        String currency = new String();
        String newCurrency = new String();
        int valueBefore = 0;

        try {
            if (listNamesListBox.getSelectedItem() == null)
            {
                showMessageDialog(null, "Select a company to convert");
            }
            else
            {
                currency = listCurrency(name);
                valueBefore = listPrice(name);
            }
            newCurrency = getCurrencyCodes().get(selectedCode).substring(0, 3);
            ConvertedField.setText("" + convert(currency,newCurrency,valueBefore));
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveConvertCurrActionPerformed

    private void detailsListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsListBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsListBoxActionPerformed

    private void listNamesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listNamesBtnActionPerformed
        listNamesListBox.removeAll();
        try {
            // TODO add your handling code here:
            textField1.setText("Loading...");
            for (int i = 0; i < listNames().size() ;i++ )
            {
                
                listNamesListBox.add(listNames().get(i));
            }
            textField1.setText("");
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listNamesBtnActionPerformed

    private void listNamesListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listNamesListBoxActionPerformed
        // TODO add your handling code here:
        detailsListBox.removeAll();
        String name = new String();
        name = listNamesListBox.getSelectedItem();
        try {
            detailsListBox.add("Symbol: " + listSymbol(name));
            detailsListBox.add("Available Shares: " + listAvailableShares(name));
            detailsListBox.add("Share Price: " + listCurrency(name) + listPrice(name));
            jSpinner1.setValue(listAvailableShares(name));

        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listNamesListBoxActionPerformed

    private void listNamesListBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNamesListBoxMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_listNamesListBoxMouseEntered

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try {
            textField1.setText("Searching...");
            searchListBox.removeAll();
            searchListBox.add(searchLowestValue());
            textField1.setText("");
        } catch (JAXBException_Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void highPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highPriceBtnActionPerformed
        try {
            textField1.setText("Searching...");
            searchListBox.removeAll();
            searchListBox.add(searchHighestPrice());
            textField1.setText("");
        } catch (Exception ex) {
            
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_highPriceBtnActionPerformed

    private void searchNameBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameBtn1ActionPerformed
        // TODO add your handling code here:
        String name = new String();
        name = nameSearchField.getText();
        searchListBox.removeAll();
        //add error handling -> if not company of that name
        try {
            if (searchName(name).isEmpty())
            {
                searchListBox.add("No companies found");
            }
            else{
                searchListBox.add("Name: " + searchName(name));
                searchListBox.add("Symbol: " + listSymbol(name));
                searchListBox.add("Available Shares: " + listAvailableShares(name));
                searchListBox.add("Share Price: " + listPrice(name));
            }

        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchNameBtn1ActionPerformed

    private void symbolSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_symbolSearchFieldActionPerformed

    private void symbolSearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symbolSearchFieldMouseClicked
        symbolSearchField.setText("");
    }//GEN-LAST:event_symbolSearchFieldMouseClicked

    private void searchSymbolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSymbolBtnActionPerformed
        // TODO add your handling code here:
        String sym = new String();
        sym = symbolSearchField.getText();
        searchListBox.removeAll();
        //add error handling -> if not company of that name
        try {
            ArrayList<String> comName = (ArrayList<String>) searchBySymbol(sym);
            textField1.setText("Searching...");
            if (searchBySymbol(sym).isEmpty())
            {
                searchListBox.add("No companies found");
            }
            else if (symbolSearchField.getText().isEmpty())
            {
                showMessageDialog(null, "Please enter a symbol to search");
            }
            else
            {
                for (int i =  0 ;i < searchBySymbol(sym).size(); i++ )
                {
                    searchListBox.add("Name: " + searchName(comName.get(i)));
                    searchListBox.add("Symbol: " + listSymbol(comName.get(i)));
                    searchListBox.add("Available Shares: " + listAvailableShares(comName.get(i)));
                    searchListBox.add("Share Price: " + listPrice(comName.get(i)));
                    searchListBox.add("");
                }
                textField1.setText("");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchSymbolBtnActionPerformed

    private void nameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSearchFieldActionPerformed

    private void nameSearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameSearchFieldMouseClicked
        nameSearchField.setText("");
    }//GEN-LAST:event_nameSearchFieldMouseClicked

    private void searchListBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchListBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchListBoxActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        searchListBox.removeAll();
        try {
            textField1.setText("Searching...");
            ArrayList<String> comName = (ArrayList<String>) searchPrice((int) jSpinner2.getValue(),(int) jSpinner3.getValue());
            if (comName.isEmpty())
            {
                searchListBox.add("No companies found");
            }
            else if ((int) jSpinner2.getValue() < 0 || (int) jSpinner3.getValue() < 0)
            {
                showMessageDialog(null,"Please enter a postive number");
            }
            else
            {
                for (int i =  0 ;i < comName.size(); i++ )
                {
                    searchListBox.add("Name: " + searchName(comName.get(i)));
                    searchListBox.add("Symbol: " + listSymbol(comName.get(i)));
                    searchListBox.add("Available Shares: " + listAvailableShares(comName.get(i)));
                    searchListBox.add("Share Price: " + listPrice(comName.get(i)));
                    searchListBox.add("");
                }

                textField1.setText("");
            }
        } catch (JAXBException_Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ShareClientGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_button6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShareClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField ConvertedField;
    private java.awt.TextField avSharesField;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.TextField compNameField;
    private java.awt.TextField compSymbolField;
    private java.awt.Button convertBtn1;
    private java.awt.TextField currencyField;
    private java.awt.List detailsListBox;
    private java.awt.Button highPriceBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Button listNamesBtn;
    private java.awt.List listNamesListBox;
    private java.awt.TextField nameSearchField;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.TextField priceField;
    private java.awt.Button removeCompany;
    private java.awt.Button saveConvertCurr;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.List searchListBox;
    private java.awt.Button searchNameBtn1;
    private java.awt.Button searchSymbolBtn;
    private java.awt.TextField symbolSearchField;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField6;
    private java.awt.Button updateShares;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> listNames() throws Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.listNames();
    }

    private static String listSymbol(java.lang.String arg0) throws Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.listSymbol(arg0);
    }

    private static int listAvailableShares(java.lang.String arg0) throws Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.listAvailableShares(arg0);
    }

    private static String listCurrency(java.lang.String arg0) throws Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.listCurrency(arg0);
    }

    private static int listPrice(java.lang.String arg0) throws Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.listPrice(arg0);
    }

    private static String searchName(java.lang.String arg0) throws Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.searchName(arg0);
    }



    private static String searchHighestPrice() throws Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.searchHighestPrice();
    }

    private static double convert(java.lang.String arg0, java.lang.String arg1, int arg2) {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.convert(arg0, arg1, arg2);
    }
public static double updateSharePrice2(String symbol) throws NumberFormatException, MalformedURLException, IOException, java.text.ParseException{ //MOVE TO SHAREBROKER
      System.out.println("symbol: " + symbol); 
      URL url = new URL("https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=" + symbol + "&apikey=VIQKMWQYY1TF44IM&datatype=JSON");
       HttpURLConnection conn = (HttpURLConnection)url.openConnection(); 
        conn.setRequestMethod("GET");
        conn.connect(); 
        String inline = new String();
        double updatedPrice = 0;
        
        int responsecode = conn.getResponseCode(); 
        System.out.println(responsecode);
        if(responsecode != 200) throw new RuntimeException("HttpResponseCode: " +responsecode);
        else
        {
            Scanner sc = new Scanner(url.openStream());
            while(sc.hasNextLine())
            {
                inline = sc.nextLine();
                System.out.println(inline);
                inline = sc.nextLine();
                if (inline.contains("close"))//get value at close
                {
                    System.out.println(inline);
                    String newPrice = inline.substring(25, 31);
                    System.out.println(newPrice);
                    updatedPrice = Double.parseDouble(newPrice);
                    break;
                }
            }
            
        }

     return updatedPrice;    
    }

    private static java.util.List<java.lang.String> getCurrencyCodes() {
        docwebservices.CurrencyConversionWSService service = new docwebservices.CurrencyConversionWSService();
        docwebservices.CurrencyConversionWS port = service.getCurrencyConversionWSPort();
        return port.getCurrencyCodes();
    }
    
    private static DefaultComboBoxModel getArray(){
        String[] arr = new String[getCurrencyCodes().size()];
        for (int i=0; i < getCurrencyCodes().size(); i++)
        {
            arr[i] = getCurrencyCodes().get(i);
        }
        DefaultComboBoxModel f = new DefaultComboBoxModel(arr);
        return f;
    }

    private static UpdateSharesResponse.Return updateShares(java.lang.String arg0, int arg1) throws FileNotFoundException_Exception, JAXBException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.updateShares(arg0, arg1);
    }

    private static ListSharesResponse.Return listShares() throws JAXBException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.listShares();
    }


    private static UpdateCurrencyPriceResponse.Return updateCurrencyPrice(java.lang.String arg0, double arg1, java.lang.String arg2) throws JAXBException_Exception, FileNotFoundException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.updateCurrencyPrice(arg0, arg1, arg2);
    }

    private static String searchLowestValue() throws JAXBException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.searchLowestValue();
    }

    private static String addCompany(java.lang.String arg0, java.lang.String arg1, int arg2, int arg3, java.lang.String arg4) throws IOException_Exception, JAXBException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.addCompany(arg0, arg1, arg2, arg3, arg4);
    }

    private static String removeCompany(java.lang.String arg0) throws JAXBException_Exception, FileNotFoundException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.removeCompany(arg0);
    }

    private static double updateSharePrice(java.lang.String arg0) throws IOException_Exception, ParseException_Exception, MalformedURLException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.updateSharePrice(arg0);
    }

    private static UpdatePriceXMLResponse.Return updatePriceXML(double arg0, java.lang.String arg1) throws FileNotFoundException_Exception, JAXBException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.updatePriceXML(arg0, arg1);
    }

    private static double getNewValue(java.lang.String arg0) {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.getNewValue(arg0);
    }


    private static java.util.List<java.lang.String> searchBySymbol(java.lang.String arg0) throws Exception_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.searchBySymbol(arg0);
    }

    private static java.util.List<java.lang.String> searchPrice(int arg0, int arg1) throws JAXBException_Exception {
        shares.ShareBroker_Service service = new shares.ShareBroker_Service();
        shares.ShareBroker port = service.getShareBrokerPort();
        return port.searchPrice(arg0, arg1);
    }




    
}
   
